=== EVERSE-ResearchSoftware/schemas/schemas/identifier_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://everse.software/identifier_schema.json",
    "type": "object",
    "default": {},
    "title": "EVERSE identifier schema",
    "required": [
        "id",
        "name",
        "description",
        "tags",
        "type",
        "subtype",
        "release-date",
        "version",
        "doi",
        "authors"
    ],
    "properties": {
        "id": {
            "type": "string",
            "default": "",
            "title": "The id of the identifier",
            "examples": [
                "linter-checks"
            ]
        },
        "name": {
            "type": "string",
            "default": "",
            "title": "The name of the identifier",
            "examples": [
                "identifier name"
            ]
        },
        "description": {
            "type": "string",
            "default": "",
            "title": "The description of the identifier",
            "examples": [
                "a short description of the identifier"
            ]
        },
        "tags": {
            "type": "array",
            "default": [],
            "title": "The tags of the identifier",
            "items": {
                "type": "string",
                "title": "A tag for the identifier",
                "enum": ["tag-1", "tag-2", "tag-3"],
                "examples": [
                    "tag-1",
                    "tag-2"
                ]
            }
        },
        "type": {
            "type": "array",
            "default": [],
            "title": "The type of the identifier",
            "items": {
                "type": "string",
                "title": "The type of the identifier",
                "examples": [
                    "fair",
                    "quality",
                    "other"
                ]
            }
        },
        "subtype": {
            "type": "array",
            "default": [],
            "title": "The subtype of the identifier",
            "items": {
                "type": "string",
                "title": "A Schema",
                "examples": [
                    "fair",
                    "accessible",
                    "interoperable",
                    "reusable"
                ]
            }
        },
        "release-date": {
            "type": "string",
            "default": "",
            "title": "The release-date of the identifier",
            "examples": [
                "01-01-1900",
                "31-12-2024"
            ],
            "format": "date",
            "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[012])-[0-9]{4}$"

        },
        "version": {
            "type": "string",
            "default": "",
            "title": "The version of the identifier",
            "examples": [
                "0.0.1",
                "v0.0.1"
            ]
        },
        "doi": {
            "type": "string",
            "default": "",
            "title": "The doi of the identifier",
            "examples": [
                "10.5281/zenodo.0000000"
            ]
        },
        "authors": {
            "type": "object",
            "default": {},
            "title": "The authors of the identifier",
            "required": [
                "name",
                "type",
                "orcid",
                "email"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "default": "",
                    "title": "The name Schema",
                    "examples": [
                        "maintainer name"
                    ]
                },
                "type": {
                    "type": "array",
                    "default": [],
                    "title": "The type Schema",
                    "items": {
                        "type": "string",
                        "title": "A Schema",
                        "examples": [
                            "individual",
                            "entity"
                        ]
                    }
                },
                "orcid": {
                    "type": "string",
                    "default": "",
                    "title": "The orcid Schema",
                    "examples": [
                        "https://orcid.org/0000-0000-0000-0000"
                    ]
                },
                "email": {
                    "type": "string",
                    "default": "",
                    "title": "The email Schema",
                    "examples": [
                        "someone@somewhere.com"
                    ]
                }
            },
            "examples": [{
                "name": "maintainer name",
                "type": [
                    "individual",
                    "entity"
                ],
                "orcid": "https://orcid.org/0000-0000-0000-0000",
                "email": "someone@somewhere.com"
            }]
        }
    }
}

=== EVERSE-ResearchSoftware/schemas/examples/identifier_example.json
{
  "id": "identifier_id",
  "name": "identifier name",
  "description": "a short description of identifier",
  "tags": [
    "tag-1",
    "tag-2"
  ],
  "type": [
    "fair",
    "quality",
    "other"
  ],
  "subtype": [
    "fair",
    "accessible",
    "interoperable",
    "reusable"
  ],
  "release-date": "09-10-2024",
  "version":"0.0.1",
  "doi": "10.5281/zenodo.0000000",
  "authors": {
    "name": "maintainer name",
    "type": [
      "individual"
    ],
    "orcid": "https://orcid.org/0000-0000-0000-0000",
    "email": "someone@somewhere.com"
  }
}

=== EVERSE-ResearchSoftware/schemas/examples/metric_example.json
{
  "id": "metric_id",
  "name": "metric name",
  "description": "a short description of metric",
  "tags": [
    "tag-1",
    "tag-2"
  ],
  "type": [
    "fair",
    "quality",
    "other"
  ],
  "subtype": [
    "fair",
    "accessible",
    "interoperable",
    "reusable"
  ],
  "release-date": "09-10-2024",
  "version":"0.0.1",
  "doi": "10.5281/zenodo.0000000",
  "authors": {
    "name": "maintainer name",
    "type": [
      "individual",
      "entity"
    ],
    "orcid": "https://orcid.org/0000-0000-0000-0000",
    "email": "someone@somewhere.com"
  }
}
